export class RegitrationTableDataType {
 constructor (
 public txtFirstName:string = '',
 public txtMiddleName:string = '',
 public txtLastName:string = '',
 public txtEmailId:number = 0,
 public dtJoiningDate:string = '',
 public dtDOB:string = '',
 public txtParentOccupation:string = '',
 public bloodGroup:string = '',
 public intReligionId:number = 0,
 public intGenderId:number = 0,
 public intCityId:number = 0,
 public txtFatherName:string = '',
 public txtMotherName:string = '',
 public txtFOccupation:string = '',
 public txtMOccupation:string = '',
 public txtFEducationalQualification:string = '',
 public txtMEducationalQualification:string = '',
 public txtAadharNumber:string = '',
 public txtNationality:string = '',
 public intSocialCategoryId:number = 0,
 public blBelongToBPL:string = '',
 public txtBPLCardNo:string = '',
 public isDisabled:string = '',
 public intDisabilityId:number = 0,
 public txtLocality:string = '',
 public txtTaluk:string = '',
 public txtDistrict:string = '',
 public intStateId:string='',
 public txtPincode:string = '',
 public txtPerAddress:string = '',
 public txtTempAddress:string = '',
 public intmothertongueId:number = 0,
 public user_type:number,
 public group_name:string=''
   
 ) { }
 static fromJson (json:any) {
  if (!json) return;

  return new RegitrationTableDataType (
  json.txtFirstName,
 json.txtMiddleName,
 json.txtLastName,
 json.txtEmailId,
 json.dtJoiningDate,
 json.dtDOB,
 json.txtParentOccupation,
 json.bloodGroup,
 json.intReligionId,
 json.intGenderId,
 json.intCityId,
 json.txtFatherName,
 json.txtMotherName,
 json.txtFOccupation,
 json.txtMOccupation,
 json.txtFEducationalQualification,
 json.txtMEducationalQualification,
 json.txtAadharNumber,
 json.txtNationality,
 json.intSocialCategoryId,
 json.blBelongToBPL,
 json.txtBPLCardNo,
 json.isDisabled,
 json.intDisabilityId,
 json.txtLocality,
 json.txtTaluk,
 json.txtDistrict,
 json.intStateId,
 json.txtPincode,
 json.txtPerAddress,
 json.txtTempAddress,
 json.intmothertongueId,
 json.user_type,
 json.group_name
  );
 }

}